// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PhishingDomainChecker
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("isPhishing")]
        public bool? IsPhishing { get; set; }

        [JsonProperty("matchedDomain")]
        public string MatchedDomain { get; set; }

        [JsonProperty("inputType")]
        public string InputType { get; set; }

        [JsonProperty("originalInput")]
        public Uri OriginalInput { get; set; }

        [JsonProperty("isPunycode")]
        public bool? IsPunycode { get; set; }

        [JsonProperty("isIpAddress")]
        public bool? IsIpAddress { get; set; }

        [JsonProperty("riskScore")]
        public long? RiskScore { get; set; }

        [JsonProperty("riskLevel")]
        public string RiskLevel { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
